"""Port of MRST example ``nearWellBoreModelingMultiSegWell``: coupled model
of the near-wellbore model (NWM) and the multi-segment well (MSW).

The MSW requires node and segment definitions, which are automatically
generated by ``MultiSegWellNWM`` through building a 'wellbore grid' (the
cells/internal faces of the wellbore grid are equivalent to the
nodes/segments of the multi-segment well).

Note on ``gridType='Voronoi'``: see the ``nearWellBoreModelingGrids.py``
module docstring for the DistMesh-randomness / retry rationale.
"""

from pathlib import Path

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

from PRSTCore.deckformat.deckinput.convert_deck_units import convert_deck_units
from PRSTCore.deckformat.deckinput.read_eclipse_deck import read_eclipse_deck
from PRSTCore.gridprocessing.compute_geometry import compute_geometry
from PRSTCore.gridprocessing.tensor_grid import tensor_grid

from PRSTCore.ad_core.simulators.simulate_schedule_ad import simulate_schedule_ad
from PRSTCore.ad_core.solvers import MUMPSSolverAD, NonLinearSolver, check_mumps
from PRSTCore.nwm.models.HorWellRegion import HorWellRegion
from PRSTCore.nwm.models.MultiSegWellNWM import MultiSegWellNWM
from PRSTCore.nwm.models.VolumeOfInterest import VolumeOfInterest
from PRSTCore.visualization import plot_cell_data

# MSW.data is the MRST module's own example data
# (mrst-2026a/modules/nwm/data/); reused here rather than duplicated.
DATA_DIR = Path(__file__).resolve().parents[3] / 'mrst-2026a' / 'modules' / 'nwm' / 'data'
OUT_DIR = Path(__file__).resolve().parent / 'output'
OUT_DIR.mkdir(exist_ok=True)


def savefig(fig, name):
    path = OUT_DIR / name
    fig.savefig(path, dpi=110, bbox_inches='tight')
    plt.close(fig)
    print(f'  wrote {path}')


def reconstruct_with_retry(VOI, WR, layerRf, *, max_attempts=3, **kwargs):
    """DistMesh's initial sampling is randomized; retry on an unlucky draw
    (see module docstring).  A persistent failure is raised rather than
    quietly substituting a different grid type."""
    last = None
    for attempt in range(1, max_attempts + 1):
        try:
            return VOI.ReConstructToUnstructuredGrid(WR, layerRf, **kwargs)
        except Exception as exc:
            last = exc
            print(f'  reconstruction attempt {attempt} failed ({exc}); retrying...')
    raise RuntimeError(
        f'VOI reconstruction (gridType={kwargs.get("gridType")!r}) did not '
        f'succeed after {max_attempts} attempts') from last


# %% Read the ECLIPSE input deck
fn = str(DATA_DIR / 'MSW.data')
deck = read_eclipse_deck(fn)
deck = convert_deck_units(deck)

# %% Build the background Cartesian grid
# MSW.data specifies a block-centred (DX/DY/DZ + TOPS) grid rather than a
# corner-point (COORD/ZCORN) one, so unlike NWM.data it cannot go through
# process_grdecl. MRST's own script builds this case with
# ``initEclipseGrid(deck)``; the direct PRSTCore equivalent for a uniform
# tensor grid with a constant top depth is ``tensor_grid`` (with a
# ``depthz`` offset) + ``compute_geometry``, matching MRST's
# ``tensorGrid``/``computeGeometry`` split.
nx, ny, nz = (int(v) for v in deck['GRID']['cartDims'])
dx = np.unique(deck['GRID']['DX'])
dy = np.unique(deck['GRID']['DY'])
dz = np.unique(deck['GRID']['DZ'])
tops = deck['GRID']['TOPS'][0]
xfaces = np.concatenate(([0.0], np.cumsum(np.full(nx, dx))))
yfaces = np.concatenate(([0.0], np.cumsum(np.full(ny, dy))))
zfaces = np.concatenate(([0.0], np.cumsum(np.full(nz, dz))))
depthz = np.full((nx + 1) * (ny + 1), tops)
GC = compute_geometry(tensor_grid(xfaces, yfaces, zfaces, depthz=depthz))

# %% Define the basic information of the horizontal well (HW)
# Define the well trajectory from the deck
compdat_recs = [c for c in deck['SCHEDULE']['COMPDAT'] if c]
compi = np.array([c[1] for c in compdat_recs], dtype=int)
compj = np.array([c[2] for c in compdat_recs], dtype=int)
compk = np.array([c[3] for c in compdat_recs], dtype=int)

pWx = dx * np.linspace(np.min(compi) - 1, np.max(compi), 15)
pWy = dy * (np.unique(compj) - 0.5) * np.ones_like(pWx)
pWz = dz * (np.unique(compk) - 0.5) * np.ones_like(pWx) + tops
pW = np.column_stack([pWx, pWy, pWz])
# Number of well segments
ns = pW.shape[0] - 1
# Define the well structure
well = {
    'name': 'PROD',
    'trajectory': pW,
    'segmentNum': ns,
    'radius': 0.1 * np.ones(ns + 1),
    'skinFactor': np.zeros(ns),
    'openedSegs': np.arange(1, ns + 1),
    'isMS': True,
    'roughness': 1e-2 * np.ones(ns),
}

# %% Build the layered unstructured VOI grid
pbdy = 100 * np.array([[4, 10], [21, 10], [21, 15], [4, 15]], dtype=float)
nextra = [1, 1]
VOI = VolumeOfInterest(GC, well, pbdy, nextra)

VOI.maxWellSegLength2D()
WR = {'ly': [15, 80], 'ny': [6, 4], 'na': 5}
VOI.volumeLayerNumber()
layerRf = [2, 2, 2]
GV = reconstruct_with_retry(VOI, WR, layerRf, multiplier=0.2, maxIter=500, gridType='Voronoi')

# %% Build the layered radial HW grid
regionIndices = [3, 8, 2, 5]
HW = HorWellRegion(GV, well, regionIndices)
radPara = {'gridType': 'gradual', 'boxRatio': [0.6, 0.6],
           'nRadCells': [10, 2], 'pDMult': 15, 'offCenter': True}
GW = HW.ReConstructToRadialGrid(radPara)

# %% Collect the simulation data
MSW = MultiSegWellNWM([GC, GV, GW], deck, well)

G = MSW.validateGlobalGrid()
fluid = MSW.setupFluid()

rockC = MSW.getCPGRockFromDeck()
rockV = MSW.getVOIRocksByInterp()
rockW = {'perm': np.tile(rockC['perm'][0, 0], (GW['cells']['num'], 3)),
         'poro': np.full(GW['cells']['num'], 0.2)}
rock = MSW.getGlobalRock([rockC, rockV, rockW])

T = MSW.getTransGloGrid(rock)
intXn = MSW.computeIntxnRelation()
nnc = MSW.generateNonNeighborConn(intXn, rock, T)
T_all, N_all = MSW.assembleTransNeighbors(T, nnc)

# Note the MSW model now only supports the 'ThreePhaseBlackOilModel'
model = MSW.setupSimModel(rock, T_all, N_all)

# %% Get the initial state by equilibrium initialization
initState = MSW.getInitState(model)

# %% Convert the simulation schedule (with and without MSW definition)
nodes = MSW.generateNodes()
segments = MSW.generateSegments()
scheduleMS = MSW.getSimSchedule(model)
schedule = MSW.getSimSchedule(model, returnMS=False)

# %% Run the simulations
nonlinear_solver = None
if check_mumps():
    print(' -- Using MUMPSSolverAD as the linear solver')
    nonlinear_solver = NonLinearSolver(linearSolver=MUMPSSolverAD())

print(' -- Running the MSW simulation (simulate_schedule_ad)')
well_sols_ms, states_ms, report_ms = simulate_schedule_ad(initState, model, scheduleMS,
                                                           nonlinear_solver=nonlinear_solver,
                                                           return_report=True)
print(f'  simulated {len(states_ms)} report steps (multi-segment well)')

print(' -- Running the standard-well simulation (simulate_schedule_ad)')
well_sols, states, report = simulate_schedule_ad(initState, model, schedule,
                                                  nonlinear_solver=nonlinear_solver,
                                                  return_report=True)
print(f'  simulated {len(states)} report steps (standard well)')

# %% Plot the saturation distribution (MSW run, final report step)
sw_final = np.asarray(states_ms[-1]['s'])
sw_final = sw_final[:, 0] if sw_final.ndim > 1 else sw_final
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
plot_cell_data(G, sw_final, ax=ax)
ax.set_title('Water saturation distribution (MSW run, final report step)')
savefig(fig, '01_saturation_distribution_msw.png')

# %% Plot the production dynamics for both runs
time_days = np.cumsum(np.asarray(scheduleMS['step']['val'], dtype=float)) / 86400.0
fig, axes = plt.subplots(3, 1, sharex=True, figsize=(7, 8))
for label, ws in (('MSW', well_sols_ms), ('standard', well_sols)):
    qWs = np.array([w[0].get('qWs', np.nan) for w in ws])
    qOs = np.array([w[0].get('qOs', np.nan) for w in ws])
    bhp = np.array([w[0].get('bhp', np.nan) for w in ws])
    axes[0].plot(time_days, qWs, marker='.', label=label)
    axes[1].plot(time_days, qOs, marker='.', label=label)
    axes[2].plot(time_days, bhp / 1e5, marker='.', label=label)
axes[0].set_ylabel('qWs [m^3/s]')
axes[1].set_ylabel('qOs [m^3/s]')
axes[2].set_ylabel('bhp [bar]')
axes[2].set_xlabel('Time [days]')
axes[0].set_title('Production dynamics: MSW vs. standard well')
axes[0].legend(fontsize=8)
fig.tight_layout()
savefig(fig, '02_production_dynamics.png')

print(f'\nAll figures written to {OUT_DIR}')
